# nextversion: '3.8'

   services:
     node-app:
       build: .
       container_name: node-app
       ports:
         - "3000:3000"
       environment:
         GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
         GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
         APP_SECRET: ${APP_SECRET}
       volumes:
         - .:/usr/src/app
       command: npm start
