version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: markdowncms
      POSTGRES_PASSWORD: changeme_into_something_secure
      POSTGRES_DB: markdowncms
    restart: always
      
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
